#region License
// Copyright (c) 2014, David Taylor
//
// Permission to use, copy, modify, and/or distribute this software for any 
// purpose with or without fee is hereby granted, provided that the above 
// copyright notice and this permission notice appear in all copies, unless 
// such copies are solely in the form of machine-executable object code 
// generated by a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES 
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR 
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF 
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#endregion License
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Xml;

namespace HotChai.Serialization.Xml
{
    public sealed class XmlObjectReader : ObjectReader
    {
        private XmlReader _reader;
        private InspectorStream _stream;
        private bool _peeking;

        public XmlObjectReader(
            Stream stream)
        {
            if (null == stream)
            {
                throw new ArgumentNullException("stream");
            }

            this._stream = new InspectorStream(stream);
            this._reader = XmlReader.Create(
                stream,
                new XmlReaderSettings()
                {
                    ConformanceLevel = ConformanceLevel.Fragment,
                    CheckCharacters = false,
                });
        }

        public override ISerializationInspector Inspector
        {
            get { return this._stream.Inspector; }

            set { this._stream.Inspector = value; }
        }

        protected override bool ReadStartObjectToken()
        {
            ReadStartElement();

            if ((this._reader.Name == XmlToken.ObjectElement) && (this._reader.IsStartElement()))
            {
                return true;
            }
            else if ((this._reader.Name == XmlToken.NullElement) && (this._reader.IsEmptyElement))
            {
                return false;
            }
            else
            {
                throw new InvalidOperationException();
            }
        }

        protected override bool ReadFirstObjectMemberKey()
        {
            if ((this._reader.Name == XmlToken.ObjectElement)
                && (this._reader.IsEmptyElement))
            {
                return false;
            }

            Peek();

            if (this._reader.Name == XmlToken.ObjectElement)
            {
                return false;
            }

            ReadStartElement();

            if (this._reader.Name != XmlToken.MemberElement)
            {
                throw new InvalidOperationException();
            }

            string memberName = this._reader.GetAttribute(XmlToken.MemberKeyAttribute);

            this.MemberKey = int.Parse(memberName, CultureInfo.InvariantCulture);

            return true;
        }

        protected override bool ReadNextObjectMemberKey()
        {
            this.ReadStartElement();

            if ((this._reader.Name != XmlToken.MemberElement) || (this._reader.IsStartElement()))
            {
                throw new InvalidOperationException();
            }

            return ReadFirstObjectMemberKey();
        }

        protected override void ReadEndObjectToken()
        {
            if ((this._reader.Name == XmlToken.ObjectElement)
                && (this._reader.IsEmptyElement))
            {
                return;
            }

            ReadPeekedEndElement(XmlToken.ObjectElement);
        }

        protected override bool ReadStartArrayToken()
        {
            ReadStartElement();

            if (this._reader.Name == XmlToken.ArrayElement)
            {
                return true;
            }
            else if (this._reader.Name == XmlToken.NullElement)
            {
                return false;
            }
            else
            {
                throw new InvalidOperationException();
            }
        }

        protected override bool ReadToFirstArrayValue()
        {
            if ((this._reader.Name == XmlToken.ArrayElement)
                && (this._reader.IsEmptyElement))
            {
                // Empty array (<array />)
                return false;
            }

            return ReadToNextArrayValue();
        }

        protected override bool ReadToNextArrayValue()
        {
            Peek();

            if ((this._reader.Name == XmlToken.ArrayElement)
                && (this._reader.NodeType == XmlNodeType.EndElement))
            {
                return false;
            }

            if ((this._reader.Name == XmlToken.NullElement)
                && (this._reader.IsEmptyElement))
            {
                return true;
            }

            if ((this._reader.Name != XmlToken.ValueElement)
                && (this._reader.Name != XmlToken.ObjectElement)
                && (this._reader.Name != XmlToken.ArrayElement))
            {
                throw new InvalidOperationException();
            }

            return true;
        }

        protected override void ReadEndArrayToken()
        {
            if ((this._reader.Name == XmlToken.ArrayElement)
                && (this._reader.IsEmptyElement))
            {
                // Empty array (<array />)
                return;
            }

            ReadPeekedEndElement(XmlToken.ArrayElement);
        }

        protected override bool ReadPrimitiveValueAsBoolean()
        {
            string valueContent = ReadPrimitiveValueAsString(1);

            if (valueContent == "1")
            {
                return true;
            }
            else if (valueContent == "0")
            {
                return false;
            }
            else
            {
                throw new InvalidOperationException("Unexpected Boolean value.");
            }
        }

        protected override int ReadPrimitiveValueAsInt32()
        {
            string valueContent = ReadPrimitiveValueAsString(25);

            return int.Parse(valueContent, CultureInfo.InvariantCulture);
        }

        protected override uint ReadPrimitiveValueAsUInt32()
        {
            string valueContent = ReadPrimitiveValueAsString(25);

            return uint.Parse(valueContent, CultureInfo.InvariantCulture);
        }

        protected override long ReadPrimitiveValueAsInt64()
        {
            string valueContent = ReadPrimitiveValueAsString(50);

            return long.Parse(valueContent, CultureInfo.InvariantCulture);
        }

        protected override ulong ReadPrimitiveValueAsUInt64()
        {
            string valueContent = ReadPrimitiveValueAsString(50);

            return ulong.Parse(valueContent, CultureInfo.InvariantCulture);
        }

        protected override float ReadPrimitiveValueAsSingle()
        {
            string valueContent = ReadPrimitiveValueAsString(25);

            return float.Parse(valueContent, CultureInfo.InvariantCulture);
        }

        protected override double ReadPrimitiveValueAsDouble()
        {
            string valueContent = ReadPrimitiveValueAsString(25);

            return double.Parse(valueContent, CultureInfo.InvariantCulture);
        }

        protected override byte[] ReadPrimitiveValueAsBytes(int quota)
        {
            // TODO: Consider CDATA

            // NOTE: Account for base-64 length expansion
            string valueContent = ReadPrimitiveValueAsString(quota * 4 / 3 + 1);
            if (null == valueContent)
            {
                return null;
            }

            return Convert.FromBase64String(valueContent);
        }

        protected override string ReadPrimitiveValueAsString(int quota)
        {
            ReadStartElement();

            if (this._reader.Name == XmlToken.NullElement)
            {
                ReadPeekedEndElement(XmlToken.NullElement);

                //this._reader.Read();

                return null;
            }

            if (this._reader.Name != XmlToken.ValueElement)
            {
                throw new InvalidOperationException();
            }

            string value;
            if (this._reader.IsEmptyElement)
            {
                value = String.Empty;
            }
            else
            {
                this._reader.Read();
                value = this._reader.ReadContentAsString();
            }

            if ((this._reader.Name != XmlToken.ValueElement)
                || ((this._reader.NodeType != XmlNodeType.EndElement) && (!this._reader.IsEmptyElement)))
            {
                throw new InvalidOperationException();
            }

            return value;
        }

        protected override MemberValueType PeekValueType()
        {
            Peek();

            if (this._reader.Name == XmlToken.ObjectElement)
            {
                return MemberValueType.Object;
            }
            else if (this._reader.Name == XmlToken.ArrayElement)
            {
                return MemberValueType.Array;
            }

            return MemberValueType.Primitive;
        }

        protected override void SkipPrimitiveValue()
        {
            // Expect to be on "value" or "null" start element
            if ((this._reader.Name != XmlToken.ValueElement)
                && (this._reader.Name != XmlToken.NullElement))
            {
                throw new InvalidOperationException();
            }

            if (this._peeking)
            {
                this._peeking = false;
            }

            if (this._reader.Name == XmlToken.NullElement)
            {
                // Expect to be an end element (<null />)
                if (!this._reader.IsEmptyElement)
                {
                    throw new InvalidOperationException();
                }
            }
            else if (this._reader.Name == XmlToken.ValueElement)
            {
                if (!this._reader.IsEmptyElement)
                {
                    ReadStartElement();

                    // Check for an empty value element
                    if (this._reader.Name == XmlToken.ValueElement)
                    {
                        // Expect to be an end element (</value>)
                        if (this._reader.NodeType != XmlNodeType.EndElement)
                        {
                            throw new InvalidOperationException();
                        }
                    }
                    else
                    {
                        // Check for expected value content
                        if ((this._reader.NodeType != XmlNodeType.Text)
                            && (this._reader.Name != XmlToken.ObjectElement)
                            && (this._reader.Name != XmlToken.ArrayElement))
                        {
                            // Unexpected nested value
                            throw new InvalidOperationException();
                        }

                        this._reader.Skip();

                        if ((this._reader.Name != XmlToken.ValueElement)
                            || (this._reader.NodeType != XmlNodeType.EndElement))
                        {
                            throw new InvalidOperationException();
                        }
                    }
                }
            }
            else
            {
                // Unexpected element (expected <value> or <null>)
                throw new InvalidOperationException();
            }
        }

        private void Peek()
        {
            if (this._peeking)
            {
                return;
            }

            this._reader.Read();

            this._peeking = true;
        }

        private void ReadStartElement()
        {
            if (this._peeking)
            {
                if (!this._reader.IsStartElement())
                {
                    throw new InvalidOperationException();
                }

                this._peeking = false;
                return;
            }

            this._reader.Read();

            //if (!this._reader.IsStartElement())
            //{
            //    throw new InvalidOperationException();
            //}
        }

        private void ReadPeekedEndElement(
            string name)
        {
            if (this._peeking)
            {
                if (this._reader.IsStartElement())
                {
                    throw new InvalidOperationException();
                }

                if (this._reader.Name != name)
                {
                    throw new InvalidOperationException("Unexpected element name.");
                }

                this._peeking = false;
                return;
            }
        }
    }
}
